### ISSUE TITLE
文檔或是例子

### ISSUE THREAD

**Issue by ShellOn** [bither/bitherj#3]
hi ! 我是看了你們寫的有關 bitcoinj 坑而轉而想使用你們的方案，
有考慮撰寫一些簡單的例子或是建立文檔嗎？ 

另外有考慮寫一下安裝方案或是提交到 maven central 嗎？
因為我想用 Clojure 開發，謝謝！

**Comment by bithernet** [comment]
当前我们还无法再文档方面投入过多的精力，因此暂时很难完善相关的文档，未来我们会逐步开始这项工作，感谢您的反馈。

完善相应文档后，我们未来会提交到 maven central 哈。

Thanks

**Comment by ShellOn** [comment]
嗯嗯完全能理解！
那請問一下你們還會對 api 做大修正嗎？

祝你們創業順利！

**Comment by bitwolaiye** [comment]
如果有升级我们也会考虑向下兼容的：）

**Comment by ShellOn** [comment]
@bitwolaiye  Cool ! Thanks your reply and waiting to hear your good news ! Good Luck !
